modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="daryanspixelmonutilitiesmod"
version="1.0.0"
displayName="Daryan's Pixelmon Utilities Mod"
displayURL="" # URL HERE
credits="" # Your name here
authors="Likeabozz123" # Your name here
description='''

'''

[[dependencies.daryanspixelmonutilitiesmod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.daryanspixelmonutilitiesmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"


[[dependencies.daryanspixelmonutilitiesmod]]
    modId="pixelmon"
    mandatory=true
    versionRange="[9.1.2,)"
    ordering="NONE"
    side="BOTH"